kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: tkg-storage-nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
parameters:
  datastoreurl: "ds:///vmfs/volumes/ddeaf657-14757c5f/"
