apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: velero
  name: minio-pv
  labels:
    app: minio
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
